import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

import java.nio.file.Files
import java.nio.file.Paths

plugins {
    id 'java'
    id 'eclipse'
    id 'maven-publish'
    id 'com.gradleup.shadow' version '9.4.1'
    id 'net.minecraftforge.gitversion' version '3.1.7'
    id 'net.minecraftforge.licenser' version '1.2.0'
    id 'net.minecraftforge.gradleutils' version '3.4.4'
    id 'net.minecraftforge.changelog' version '3.2.1'
    id 'net.minecraftforge.multi-release' version '0.1.4'
}

gradleutils.displayName = 'Installer'
group = 'net.minecraftforge'
version = gitversion.tagOffset
println "Version: $version"

repositories {
    mavenCentral()
    maven gradleutils.forgeMaven
}

license {
    header = file('LICENSE-header.txt')
    newLine = false
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(8)
    withSourcesJar()
}

test {
  useJUnitPlatform()
}

dependencies {
    implementation(libs.jopt.simple)
    implementation(libs.gson)
    testImplementation(libs.junit.api)
    testRuntimeOnly(libs.bundles.junit.runtime)
}

Files.list(Paths.get(projectDir.absolutePath))
        .filter(Files::isRegularFile)
        .filter(path -> path.getFileName().toString().endsWith('-installer.jar'))
        .findFirst()
        .ifPresent(path -> {
            var firstFile = path.toFile()
            logger.lifecycle("Detected test installer: ${firstFile.name}")
            dependencies.implementation(files(firstFile))
        })

tasks.named('jar', Jar) {
    manifest {
        attributes([
            'Main-Class': 'net.minecraftforge.installer.SimpleInstaller',
            'Enable-Native-Access': 'ALL-UNNAMED'
        ])
        attributes([
            'Specification-Title':    'Installer',
            'Specification-Vendor':   'Forge Development LLC',
            'Specification-Version':   gitversion.info.tag,
            'Implementation-Title':   'SimpleInstaller',
            'Implementation-Vendor':  'Forge Development LLC',
            'Implementation-Version':  project.version
        ] as LinkedHashMap, 'net/minecraftforge/installer/')
    }

    archiveClassifier = 'java8'
}

multiRelease.register {
    add(JavaLanguageVersion.of(22), project(':installer-java22'))
}

tasks.named('multiReleaseJar', Jar) {
    archiveClassifier = ''
}

tasks.named('shadowJar', ShadowJar) {
    dependsOn tasks.named('multiReleaseJar')

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from({
        zipTree(tasks.named('multiReleaseJar').get().archiveFile.get().asFile)
    })

    archiveClassifier = 'fatjar'
    minimize()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

artifacts {
    archives shadowJar
}

changelog {
    fromBase()
}

publishing {
    publications.register('mavenJava', MavenPublication) {
        changelog.publish(it)
        gradleutils.promote(it)

        from components.java

        artifactId = 'installer'

        pom {
            name = 'Installer'
            description = 'Minecraft Forge Installer'
            url = 'https://github.com/MinecraftForge/Installer'

            gradleutils.pom.addRemoteDetails(pom)

            license gradleutils.pom.licenses.LGPLv2_1

            developers {
                developer gradleutils.pom.developers.LexManos
            }
        }
    }

    repositories {
        maven gradleutils.publishingForgeMaven
    }
}
